### PR TITLE
fix: bug 1842 - web chat active selection background

### PR DESCRIPTION
**Pull request by pnwbrian**
Switched to orange/maroon palette for active selection

- Queued for team review

### CODE REVIEW

**Comment by mattmazzola** [comment]
I find it easier to review things like this if there is a visual. I know we move fast and it's not always necessary to take the pictures but here there for anyone else who needed to see the change:

**Before:**
image

**After:**
image

I think it is an improvement because the red made it look like it was highlighted due to error.

Unrelated to this specific change but my thoughts about web chat look:

- Prefer to get rid of the stroke around the User Bot buttons. It makes the buttons look blurry or unfocused. I see that the strke is also the color of the "+" sign inside so this makes it difficult.

Example:
image

- Would maybe put white circle or something behind the trashcan to have more clickable boundaries of a button and be more visible. Red loses contrast on the orange. 

Example:
image

**Comment by pnwbrian** [comment]
Deferring trash icon changes

**Comment by pnwbrian** [comment]
Deferring lower priority trash can icon changes

**Pull request merged**
